/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seyahatacentesi;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static seyahatacentesi.Odeme.seferId;
import static seyahatacentesi.Odeme.tc;

/**
 *
 * @author myavuz
 */
public class OtelOdeme extends javax.swing.JFrame {

    /**
     * Creates new form OtelOdeme
     */
    public static int tc;
    public static int odaId;
    public static int kullanilacakPuan;
    public static boolean puanKullanabilir = false;

    public static void getInfo(int odaid) {
        odaId = odaid;

    }

    public static void getInfo(String id) {
        tc = Integer.parseInt(id);

    }

    public OtelOdeme() {
        initComponents();
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        System.out.println(odaId);
        System.out.println(tc);


        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
            String sorgu = "SELECT * FROM MUSTERI";

            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(sorgu);

            while (rs.next()) {

                if (Integer.parseInt(rs.getString("TC")) == tc) {

                    lbl_puan.setText("PUANINIZ: " + rs.getString("PUAN"));
                    break;
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        String girisTarihi = "";
            String cikisTarihi = "";
            int OdaFiyati = 0;
            int odenecekFiyat = 0;

            Calendar cal1 = new GregorianCalendar();
            Calendar cal2 = new GregorianCalendar();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                String sorgu = "SELECT * FROM OTEL WHERE ODA_ID=" + odaId;

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery(sorgu);

                if (rs.next()) {

                    girisTarihi = rs.getString("GIRIS_TARIHI");
                    cikisTarihi = rs.getString("CIKIS_TARIHI");
                    OdaFiyati = Integer.parseInt(rs.getString("ODA_FIYATI"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
            }

            Date date;
            try {
                date = sdf.parse(girisTarihi);
                cal1.setTime(date);
                date = sdf.parse(cikisTarihi);
                cal2.setTime(date);
            } catch (ParseException ex) {
                Logger.getLogger(OtelOdeme.class.getName()).log(Level.SEVERE, null, ex);
            }

            int gunSayisi = daysBetween(cal1.getTime(), cal2.getTime());
            odenecekFiyat = gunSayisi * OdaFiyati;
            System.out.println(odenecekFiyat);
            
        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
            String sorgu = "SELECT * FROM OTEL";

            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(sorgu);

            while (rs.next()) {

                if (Integer.parseInt(rs.getString("ODA_ID")) == odaId) {

                    lbl_tutar.setText(odenecekFiyat+"");
                    lbl_bonusPuan.setText("SATIN ALACAĞINIZ BİLET İLE KAZANACAĞINIZ PUAN: " + rs.getString("OTEL_PUAN"));
                    break;
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_kartAdi = new javax.swing.JTextField();
        txt_kartNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jYearChooser_SKT = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        lbl_puan = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton_SatinAl = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lbl_tutar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox_tercih = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jSpinner_puan = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        lbl_indirim = new javax.swing.JLabel();
        jButton_puanKullan = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox_ay = new javax.swing.JComboBox<>();
        lbl_bonusPuan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 204));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SEYAHAT ACENTESİ");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BİLET-TATİL SİSTEMİ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seyahatacentesi/images/icon.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seyahatacentesi/images/back.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(799, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 110));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("KART ÜZERİNDEKİ AD SOYAD");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("KART NUMARASI");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seyahatacentesi/images/star.png"))); // NOI18N

        lbl_puan.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_puan.setForeground(new java.awt.Color(0, 51, 153));
        lbl_puan.setText("PUANINIZ: ");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("SON KULLANMA TARİHİ");

        jButton_SatinAl.setBackground(new java.awt.Color(0, 51, 204));
        jButton_SatinAl.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton_SatinAl.setForeground(new java.awt.Color(255, 255, 255));
        jButton_SatinAl.setText("SATIN AL");
        jButton_SatinAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SatinAlActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setText("TUTAR:");

        lbl_tutar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 153));
        jLabel19.setText("TL");

        jCheckBox_tercih.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBox_tercih.setForeground(new java.awt.Color(0, 51, 153));
        jCheckBox_tercih.setText("Ödeme için puan kullanmak istiyorum.");
        jCheckBox_tercih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_tercihActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("KULLANILACAK PUAN:");

        jSpinner_puan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_puanStateChanged(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 153));
        jLabel20.setText("PUAN İNDİRİMİ: ");

        lbl_indirim.setText("0");

        jButton_puanKullan.setBackground(new java.awt.Color(0, 51, 204));
        jButton_puanKullan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton_puanKullan.setForeground(new java.awt.Color(255, 255, 255));
        jButton_puanKullan.setText("PUAN KULLAN");
        jButton_puanKullan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_puanKullanActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 153));
        jLabel21.setText("TL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_tercih)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_puan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_indirim, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_puanKullan)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_tercih)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinner_puan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbl_indirim)
                    .addComponent(jLabel21))
                .addGap(42, 42, 42)
                .addComponent(jButton_puanKullan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jComboBox_ay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık" }));

        lbl_bonusPuan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_bonusPuan.setForeground(new java.awt.Color(153, 0, 0));
        lbl_bonusPuan.setText("SATIN ALACAĞINIZ BİLET İLE KAZANACAĞINIZ PUAN: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jButton_SatinAl, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_puan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(58, 58, 58)
                                .addComponent(jComboBox_ay, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jYearChooser_SKT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_bonusPuan)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kartNo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kartAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lbl_puan)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_bonusPuan)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kartAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_kartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jComboBox_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jYearChooser_SKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lbl_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(42, 42, 42)
                .addComponent(jButton_SatinAl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1040, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        setVisible(false);
        dispose();
        new KayitYap().setVisible(true);
    }//GEN-LAST:event_jLabel12MousePressed

    private void jButton_SatinAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SatinAlActionPerformed

        if (txt_kartAdi.getText().compareTo("") != 0 || txt_kartNo.getText().compareTo("") != 0) {

            int eskiPuan = 0;
            int otelPuan = 0;
            String isim = "";
            String soyisim = "";
            String firma = "";
            String odaTipi = "";
            String girisTarihi = "";
            String cikisTarihi = "";
            int OdaFiyati = 0;
            int odenecekFiyat = 0;

            //MUSTERI KART BILGILERI SET
            if (txt_kartAdi.getText().compareTo("") != 0 || txt_kartNo.getText().compareTo("") != 0) {
                String kartAdi = txt_kartAdi.getText();
                String kartNo = txt_kartNo.getText();
                String ay = jComboBox_ay.getSelectedItem().toString();
                int yil = jYearChooser_SKT.getYear();

                try {

                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                    String sorgu = "SELECT * FROM MUSTERI WHERE TC=" + tc;

                    Statement stmt = con.createStatement();

                    ResultSet rs = stmt.executeQuery(sorgu);

                    if (rs.next()) {
                        eskiPuan = Integer.parseInt(rs.getString("PUAN"));
                        isim = rs.getString("ISIM");
                        soyisim = rs.getString("SOYISIM");

                        System.out.println("UPDATE MUSTERI SET KART_ADI='" + kartAdi + "', KART_NO='" + kartNo + "', KART_SKT_M='" + ay + "', KART_SKT_Y=" + yil + " WHERE TC=" + tc + "");
                        stmt.executeUpdate("UPDATE MUSTERI SET KART_ADI='" + kartAdi + "', KART_NO='" + kartNo + "', KART_SKT_M='" + ay + "', KART_SKT_Y=" + yil + " WHERE TC=" + tc + "");

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(GirisYap.class.getName()).log(Level.ALL.SEVERE, null, ex);
                }

            }

            //OTEL PUAN ALMA
            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                String sorgu = "SELECT * FROM OTEL WHERE ODA_ID=" + odaId;

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery(sorgu);

                if (rs.next()) {
                    firma = rs.getString("OTEL_FIRMA");
                    odaTipi = rs.getString("ODA_TIPI");
                    girisTarihi = rs.getString("GIRIS_TARIHI");
                    cikisTarihi = rs.getString("CIKIS_TARIHI");
                    otelPuan = Integer.parseInt(rs.getString("OTEL_PUAN"));
                    OdaFiyati = Integer.parseInt(rs.getString("ODA_FIYATI"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
            }

            Calendar cal1 = new GregorianCalendar();
            Calendar cal2 = new GregorianCalendar();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

            Date date;
            try {
                date = sdf.parse(girisTarihi);
                cal1.setTime(date);
                date = sdf.parse(cikisTarihi);
                cal2.setTime(date);
            } catch (ParseException ex) {
                Logger.getLogger(OtelOdeme.class.getName()).log(Level.SEVERE, null, ex);
            }

            int gunSayisi = daysBetween(cal1.getTime(), cal2.getTime());
            odenecekFiyat = gunSayisi * OdaFiyati;

            //MUSTERI PUAN GUNCELLEME
            if (puanKullanabilir == true) {

                int yeniPuan = eskiPuan - Integer.parseInt(jSpinner_puan.getValue().toString()) + otelPuan;
                try {

                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                    String sorgu = "SELECT * FROM MUSTERI WHERE TC=" + tc;

                    Statement stmt = con.createStatement();

                    ResultSet rs = stmt.executeQuery(sorgu);

                    if (rs.next()) {
                        System.out.println("UPDATE MUSTERI SET PUAN=" + yeniPuan + " WHERE TC=" + tc + "");
                        stmt.executeUpdate("UPDATE MUSTERI SET PUAN=" + yeniPuan + " WHERE TC=" + tc + "");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {

                try {

                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                    String sorgu = "SELECT * FROM MUSTERI WHERE TC=" + tc;

                    Statement stmt = con.createStatement();

                    ResultSet rs = stmt.executeQuery(sorgu);

                    int bonussuzPuan = eskiPuan + otelPuan;
                    if (rs.next()) {
                        System.out.println("UPDATE MUSTERI SET PUAN=" + bonussuzPuan + " WHERE TC=" + tc + "");
                        stmt.executeUpdate("UPDATE MUSTERI SET PUAN=" + bonussuzPuan + " WHERE TC=" + tc + "");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            //DURUM DEGISTIRME
            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                String sorgu = "SELECT * FROM OTEL WHERE ODA_ID=" + odaId;

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery(sorgu);

                if (rs.next()) {

                    stmt.executeUpdate("UPDATE OTEL SET DURUM='Kiralanmış' WHERE ODA_ID=" + odaId);
                }

            } catch (SQLException ex) {
                Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                Statement s2 = con.createStatement();
                String sql = "SELECT MAX(REZERVASYON_ID) MAX_ID FROM REZERVASYON";
                ResultSet idMax = s2.executeQuery(sql);
                int rezervasyonId = 0;

                if (idMax.next()) {
                    rezervasyonId = idMax.getInt("MAX_ID") + 1;
                }

                Statement s3 = con.createStatement();
                String sorgu2 = "INSERT INTO REZERVASYON (REZERVASYON_ID, TC , ODA_ID , ISIM ,SOYISIM ,ODA_TIPI ,GIRIS_TARIHI,CIKIS_TARIHI, OTEL_FIRMA,FIYAT) VALUES ("
                        + rezervasyonId + "," + tc + "," + odaId + ",'" + isim + "', '" + soyisim + "', '" + odaTipi
                        + "','" + girisTarihi + "','" +firma+"','" + cikisTarihi + "'," + odenecekFiyat + ")";

                s3.executeUpdate(sorgu2);

            } catch (SQLException ex) {
                Logger.getLogger(Odeme.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(rootPane, "KAYIT BAŞARILI.", "", HEIGHT);
            setVisible(false);
            dispose();
            new IslemSec().setVisible(true);
        } else {

            JOptionPane.showMessageDialog(rootPane, "BOŞ ALANLARI DOLDURUNUZ.", "", HEIGHT);
        }
    }//GEN-LAST:event_jButton_SatinAlActionPerformed

    private void jCheckBox_tercihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_tercihActionPerformed
        if (jCheckBox_tercih.isSelected()) {
            jSpinner_puan.setEnabled(true);
            jButton_puanKullan.setEnabled(true);
            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jLabel14.setForeground(new java.awt.Color(0, 51, 153));
            jLabel20.setForeground(new java.awt.Color(0, 51, 153));
            jLabel21.setForeground(new java.awt.Color(0, 51, 153));

        } else {
            jSpinner_puan.setEnabled(false);
            jButton_puanKullan.setEnabled(false);
            jPanel1.setBackground(new java.awt.Color(240, 240, 240));
            jLabel14.setForeground(new java.awt.Color(102, 102, 102));
            jLabel20.setForeground(new java.awt.Color(102, 102, 102));
            jLabel21.setForeground(new java.awt.Color(102, 102, 102));

            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                String sorgu = "SELECT * FROM MUSTERI";

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery(sorgu);

                while (rs.next()) {

                    if (Integer.parseInt(rs.getString("TC")) == tc) {

                        lbl_puan.setText("PUANINIZ: " + rs.getString("PUAN"));
                        break;
                    }

                }

            } catch (SQLException ex) {
                Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
            }

            String girisTarihi = "";
            String cikisTarihi = "";
            int OdaFiyati = 0;
            int odenecekFiyat = 0;

            Calendar cal1 = new GregorianCalendar();
            Calendar cal2 = new GregorianCalendar();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                String sorgu = "SELECT * FROM OTEL WHERE ODA_ID=" + odaId;

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery(sorgu);

                if (rs.next()) {

                    girisTarihi = rs.getString("GIRIS_TARIHI");
                    cikisTarihi = rs.getString("CIKIS_TARIHI");
                    OdaFiyati = Integer.parseInt(rs.getString("ODA_FIYATI"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
            }

            Date date;
            try {
                date = sdf.parse(girisTarihi);
                cal1.setTime(date);
                date = sdf.parse(cikisTarihi);
                cal2.setTime(date);
            } catch (ParseException ex) {
                Logger.getLogger(OtelOdeme.class.getName()).log(Level.SEVERE, null, ex);
            }

            int gunSayisi = daysBetween(cal1.getTime(), cal2.getTime());
            odenecekFiyat = gunSayisi * OdaFiyati;

            try {

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
                String sorgu = "SELECT * FROM OTEL";

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery(sorgu);

                while (rs.next()) {

                    if (Integer.parseInt(rs.getString("ODA_ID")) == odaId) {

                        lbl_tutar.setText(odenecekFiyat + "");
                        lbl_bonusPuan.setText("SATIN ALACAĞINIZ BİLET İLE KAZANACAĞINIZ PUAN: " + rs.getString("OTEL_PUAN"));
                        break;
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jCheckBox_tercihActionPerformed

    private void jSpinner_puanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_puanStateChanged

        kullanilacakPuan = Integer.parseInt(jSpinner_puan.getValue().toString());
        lbl_indirim.setText("" + kullanilacakPuan * 2);
    }//GEN-LAST:event_jSpinner_puanStateChanged

    private void jButton_puanKullanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_puanKullanActionPerformed
        kullanilacakPuan = Integer.parseInt(jSpinner_puan.getValue().toString());
        System.out.println(kullanilacakPuan);

        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SeyahatAcentesiDB", "sa", "as");
            String sorgu = "SELECT * FROM MUSTERI WHERE TC=" + tc;

            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(sorgu);

            while (rs.next()) {
                int puan = Integer.parseInt(rs.getString("PUAN"));
                if (puan >= kullanilacakPuan && (puan != 0)) {
                    System.out.println("geldi");
                    puanKullanabilir = true;
                    break;
                }
                if (puan < kullanilacakPuan || puan == 0) {
                    System.out.println("geldi2");
                    JOptionPane.showMessageDialog(rootPane, "YETERLİ PUANINIZ YOK.", "", HEIGHT);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(GirisYap.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (puanKullanabilir) {
            System.out.println("kullanabilir");
            lbl_tutar.setText(Integer.parseInt(lbl_tutar.getText()) - Integer.parseInt(lbl_indirim.getText()) + "");
        }
    }//GEN-LAST:event_jButton_puanKullanActionPerformed

    public int daysBetween(Date d1, Date d2) {
        return (int) ((d2.getTime() - d1.getTime()) / (1000 * 60 * 60 * 24));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtelOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtelOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtelOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtelOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtelOdeme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SatinAl;
    private javax.swing.JButton jButton_puanKullan;
    private javax.swing.JCheckBox jCheckBox_tercih;
    private javax.swing.JComboBox<String> jComboBox_ay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner jSpinner_puan;
    private com.toedter.calendar.JYearChooser jYearChooser_SKT;
    private javax.swing.JLabel lbl_bonusPuan;
    private javax.swing.JLabel lbl_indirim;
    private javax.swing.JLabel lbl_puan;
    private javax.swing.JLabel lbl_tutar;
    private javax.swing.JTextField txt_kartAdi;
    private javax.swing.JTextField txt_kartNo;
    // End of variables declaration//GEN-END:variables
}
